# Generated by Django 3.2.15 on 2025-03-10 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0019_auto_20250305_0256'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0021_remove_document_aliment'),
        ('sinistre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(blank=True, null=True)),
                ('prenoms', models.TextField(blank=True, null=True)),
                ('portable', models.TextField(blank=True, null=True)),
                ('telephone', models.TextField(blank=True, null=True)),
                ('fax', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('code_postal', models.TextField(blank=True, null=True)),
                ('boite_postale', models.TextField(blank=True, null=True)),
                ('ville', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pays', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.pays')),
                ('type_intervenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.typeintervenant')),
            ],
            options={
                'verbose_name': 'Intervenants',
                'verbose_name_plural': 'Intervenants',
                'db_table': 'intervenant',
            },
        ),
        migrations.CreateModel(
            name='MouvementSinistre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.CharField(blank=True, max_length=255, null=True)),
                ('date_effet', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('statut_validite', models.CharField(choices=[('VALIDE', 'Valide'), ('SUPPRIME', 'Supprime'), ('BROUILLON', 'Brouillon'), ('CLOTURE', 'Cloture')], default='VALIDE', max_length=15, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('motif', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='production.motif')),
                ('mouvement', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='production.mouvement')),
                ('police', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='production.police')),
            ],
            options={
                'verbose_name': 'Mouvement du sinistre',
                'verbose_name_plural': 'Mouvements du sinistre',
                'db_table': 'mouvements_sinistres',
            },
        ),
        migrations.AlterModelOptions(
            name='sinistre',
            options={'permissions': [('can_do_saisie_prestataire', 'Peut saisir des PEC en ligne'), ('can_do_saisie_gestionnaire', 'Peut saisir des PEC physiques'), ('can_view_prestations', 'Peut afficher les PEC'), ('can_do_generation_bordereau_facturation', 'Peut générer un bordereau de facturation'), ('can_view_bordereaux_facturations', 'Peut voir bordereaux de facturations'), ('can_view_facturesprestataires_en_attente', 'Peut voir les factures prestataire en attente'), ('can_view_facturesprestataires_validees', 'Peut voir les factures prestataire validées'), ('can_do_traitement_factures_prestataire', 'Peut traiter les factures prestataires'), ('can_view_remboursements_validees', 'Peut voir les remboursements validées'), ('can_do_ordonnancement', 'Peut faire un ordonnancement'), ('can_view_bordereaux_ordonnancement', "Peut voir les bordereaux d'ordonnancements"), ('can_do_annulation_sinistre', 'Peut annuler des sinistres'), ('can_do_annulation_facture', 'Peut annuler des factures')], 'verbose_name': 'Sinistres', 'verbose_name_plural': 'Sinistres'},
        ),
        migrations.RenameField(
            model_name='sinistre',
            old_name='date_entree',
            new_name='date_cloture',
        ),
        migrations.RenameField(
            model_name='sinistre',
            old_name='date_ordonnancement',
            new_name='date_declaration',
        ),
        migrations.RenameField(
            model_name='sinistre',
            old_name='date_sortie',
            new_name='date_ouverture',
        ),
        migrations.RenameField(
            model_name='sinistre',
            old_name='reviewed_at',
            new_name='date_reouverture',
        ),
        migrations.RenameField(
            model_name='sinistre',
            old_name='depassement',
            new_name='franchise',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='acte',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='adherent_principal',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='affection',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='aliment',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='approuved_by',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='bareme',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='bordereau_ordonnancement',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='date_reception_facture',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='delai_controle',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='deleted_author',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='depassement_accepte',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='dossier_sinistre',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='facture_compagnie',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='facture_prestataire',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='far',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='formulegarantie',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='frais_reel',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='frais_reel_accepte',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='franchise_max',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='franchise_min',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='frequence',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='import_stats',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='is_ges_processed',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='medicament',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='montant_base_remboursement',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='montant_plafond',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='montant_refacture_client',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='montant_refacture_compagnie',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='montant_remboursement_accepte',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='montant_remboursement_refuse',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='motif_refus_remboursement',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='motif_rejet',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='motif_rejet_ordonnancement',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='motif_suppression',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='nature',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='net_regle',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='nombre_accorde',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='nombre_demande',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='nombre_demande_initial',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='nombre_plafond',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='numero_bordereau',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='numero_lettre_cheque',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='observation',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='paiement_comptable',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='part_assure',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='part_assure_accepte',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='part_compagnie',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='part_compagnie_accepte',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='periode_couverture',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='plafond_chambre',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='plafond_hospit',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='prescripteur',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='prestataire',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='prix_unitaire',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='recalcule_mt_refact_garant_client',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='reference_facture',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='served_by',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='soins_a_l_entrange',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='statut_bordereau',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='statut_prestation',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='statut_synchro_veos',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='taux_retenue',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='taux_tm',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='ticket_moderateur',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='ticket_prefinance',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='tps',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='type_prefinancement',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='unite_frequence',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='updated_price_by',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='veos_code_acte',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='veos_code_affection',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='veos_code_aliment',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='veos_code_cie',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='veos_code_prescripteur',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='veos_code_prestataire',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='veos_id_npol',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='veos_id_sin',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='veos_numero_sin',
        ),
        migrations.AddField(
            model_name='sinistre',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.client'),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='fait_generateur',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='lieu_survenance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='point_de_choc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='sinistre_recours',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non'), ('AUCUN', 'Aucun')], default='AUCUN', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='tva_recuperee',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='updated_by_sinistre', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_by_sinistre', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='statut',
            field=models.CharField(choices=[('ACCORDE', 'Accorde'), ('EN ATTENTE', 'Attente'), ('REJETE', 'Rejete')], default='EN ATTENTE', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='statut_validite',
            field=models.CharField(choices=[('VALIDE', 'Valide'), ('SUPPRIME', 'Supprime'), ('BROUILLON', 'Brouillon'), ('CLOTURE', 'Cloture')], default='BROUILLON', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='type_sinistre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.typesinistre'),
        ),
        migrations.CreateModel(
            name='SinistreIntervenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intervenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='sinistre.intervenant')),
                ('sinistre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='sinistre.sinistre')),
            ],
            options={
                'verbose_name': 'Sinistre intervenant',
                'verbose_name_plural': 'Sinistre intervenant',
                'db_table': 'sinistre_intervenant',
            },
        ),
        migrations.CreateModel(
            name='ReglementSinistre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('sinistre', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sinistre.sinistre')),
            ],
            options={
                'verbose_name': 'Règlement du sinistre',
                'verbose_name_plural': 'Règlement du sinistre',
                'db_table': 'reglement_sinistres',
            },
        ),
        migrations.CreateModel(
            name='Provision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimation', models.DecimalField(decimal_places=16, max_digits=50, null=True)),
                ('deja_regle', models.DecimalField(decimal_places=16, max_digits=50, null=True)),
                ('provision', models.DecimalField(decimal_places=16, max_digits=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('garantie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.garantie')),
                ('poste_dommage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.postedommage')),
                ('sinistre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='sinistre.sinistre')),
            ],
            options={
                'verbose_name': 'Provisions',
                'verbose_name_plural': 'Provisions',
                'db_table': 'provisions',
            },
        ),
        migrations.CreateModel(
            name='OperationSaisie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('mouvement_sinistre', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sinistre.mouvementsinistre')),
            ],
            options={
                'verbose_name': 'Opération de saisie',
                'verbose_name_plural': 'Opération de saisie',
                'db_table': 'operation_saisie',
            },
        ),
        migrations.AddField(
            model_name='mouvementsinistre',
            name='sinistre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sinistre.sinistre'),
        ),
        migrations.CreateModel(
            name='GarantieSinistre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('franchise', models.DecimalField(decimal_places=16, max_digits=50, null=True)),
                ('capital', models.DecimalField(decimal_places=16, max_digits=50, null=True)),
                ('prime_nette', models.DecimalField(decimal_places=16, max_digits=50, null=True)),
                ('prime_ttc', models.DecimalField(decimal_places=16, max_digits=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('circonstance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.circonstance')),
                ('garantie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.garantie')),
                ('responsabilite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.responsabilite')),
            ],
            options={
                'verbose_name': 'Garantie Sinistre',
                'verbose_name_plural': 'Garantie Sinistre',
                'db_table': 'garantie_sinistre',
            },
        ),
        migrations.CreateModel(
            name='AlimentPoliceSinistre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risque', models.TextField(blank=True, null=True)),
                ('aliment_police', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.alimentpolice')),
                ('police', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='police_sinistre', to='production.police')),
                ('sinistre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='aliment_police_sinistre', to='production.police')),
            ],
            options={
                'verbose_name': 'Sinistre aliment police',
                'verbose_name_plural': 'Sinistre aliment police',
                'db_table': 'aliment_police_sinistre',
            },
        ),
    ]
