# Generated by Django 4.2.20 on 2025-04-10 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0011_rename_risqueproduit_tauxcommission_and_more'),
        ('sinistre', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SinistreEnRecours',
        ),
    ]
