# Generated by Django 3.2.15 on 2025-03-10 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0021_remove_document_aliment'),
        ('sinistre', '0002_auto_20250310_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentpolicesinistre',
            name='aliment_police',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='aliment_sinistre', to='production.alimentpolice'),
        ),
        migrations.AlterField(
            model_name='alimentpolicesinistre',
            name='sinistre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='aliment_police_sinistre', to='sinistre.sinistre'),
        ),
    ]
