# Generated by Django 4.2.20 on 2025-04-10 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0002_sinistreetape_delete_sinistreenrecours'),
    ]

    operations = [
        #migrations.DeleteModel(
        #    name='SinistreEtape',
        #),
    ]
