# Generated by Django 4.2.20 on 2025-04-10 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0011_rename_risqueproduit_tauxcommission_and_more'),
        ('sinistre', '0003_delete_sinistreetape'),
    ]

    operations = [
        migrations.CreateModel(
            name='SinistreEtape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordre', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etape_sinistre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.etapesinistre')),
                ('sinistre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='sinistre.sinistre')),
            ],
            options={
                'verbose_name': 'Sinistre étape',
                'verbose_name_plural': 'Sinistre étape',
                'db_table': 'sinistre_etape',
            },
        ),
    ]
