# Generated by Django 3.2.15 on 2025-03-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0003_auto_20250310_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garantiesinistre',
            name='capital',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='garantiesinistre',
            name='franchise',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='garantiesinistre',
            name='prime_nette',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='garantiesinistre',
            name='prime_ttc',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='deja_regle',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='estimation',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='provision',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='franchise',
            field=models.BigIntegerField(null=True),
        ),
    ]
