# Generated by Django 3.2.15 on 2025-03-11 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sinistre', '0004_auto_20250310_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementsinistre',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='updated_by_sinistre_mouv', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mouvementsinistre',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_by_sinistre_mouv', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='OperationSaisie',
        ),
    ]
