# Generated by Django 4.2.20 on 2025-04-13 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sinistre', '0004_sinistreetape'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historiquesinistre',
            options={'verbose_name': 'Historique Sinistres', 'verbose_name_plural': 'Historique Sinistres'},
        ),
        migrations.RemoveField(
            model_name='historiquesinistre',
            name='bureau',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='bureau',
        ),
        migrations.AddField(
            model_name='historiquesinistre',
            name='autre_circonstance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='autre_circonstance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sinistreetape',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
