# Generated by Django 3.2.15 on 2025-03-12 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0020_garantiecirconstance'),
        ('sinistre', '0005_auto_20250311_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garantiesinistre',
            name='responsabilite',
        ),
        migrations.AddField(
            model_name='sinistre',
            name='responsabilite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.responsabilite'),
        ),
    ]
