# Generated by Django 3.2.15 on 2025-03-12 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0020_garantiecirconstance'),
        ('sinistre', '0006_auto_20250312_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinistre',
            name='date_reglement',
        ),
        migrations.AddField(
            model_name='reglementsinistre',
            name='date_reglement',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='reglementsinistre',
            name='devise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.devise'),
        ),
        migrations.AddField(
            model_name='reglementsinistre',
            name='mode_reglement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.modereglement'),
        ),
        migrations.AddField(
            model_name='reglementsinistre',
            name='montant_regle',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reglementsinistre',
            name='provision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='sinistre.provision'),
        ),
        migrations.AddField(
            model_name='reglementsinistre',
            name='sinistre_intervenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='sinistre.sinistreintervenant'),
        ),
        migrations.AlterField(
            model_name='reglementsinistre',
            name='sinistre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='sinistre.sinistre'),
        ),
    ]
