# Generated by Django 3.2.15 on 2025-03-13 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0007_auto_20250312_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='garantiesinistre',
            name='sinistre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='sinistre.sinistre'),
        ),
        migrations.AlterField(
            model_name='dossiersinistre',
            name='statut_pec',
            field=models.CharField(choices=[('ACCORDE', 'Accorde'), ('EN ATTENTE', 'Attente'), ('REJETE', 'Rejete'), ('EN RECOURS', 'En Recours'), ('SOLDE', 'Solde')], default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='dossiersinistre',
            name='statut_prorogation',
            field=models.CharField(choices=[('ACCORDE', 'Accorde'), ('EN ATTENTE', 'Attente'), ('REJETE', 'Rejete'), ('EN RECOURS', 'En Recours'), ('SOLDE', 'Solde')], default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='prorogationsinistre',
            name='statut',
            field=models.CharField(choices=[('ACCORDE', 'Accorde'), ('EN ATTENTE', 'Attente'), ('REJETE', 'Rejete'), ('EN RECOURS', 'En Recours'), ('SOLDE', 'Solde')], default='EN ATTENTE', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='statut',
            field=models.CharField(choices=[('ACCORDE', 'Accorde'), ('EN ATTENTE', 'Attente'), ('REJETE', 'Rejete'), ('EN RECOURS', 'En Recours'), ('SOLDE', 'Solde')], default='EN ATTENTE', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sinistretemporaire',
            name='statut',
            field=models.CharField(choices=[('ACCORDE', 'Accorde'), ('EN ATTENTE', 'Attente'), ('REJETE', 'Rejete'), ('EN RECOURS', 'En Recours'), ('SOLDE', 'Solde')], default='ACCORDE', max_length=15, null=True),
        ),
    ]
