# Generated by Django 3.2.15 on 2025-03-13 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0008_auto_20250313_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garantiesinistre',
            name='sinistre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='garanties', to='sinistre.sinistre'),
        ),
    ]
