# Generated by Django 3.2.15 on 2025-03-13 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0022_document_sinistre'),
        ('configurations', '0020_garantiecirconstance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sinistre', '0009_alter_garantiesinistre_sinistre'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueSinistre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('lieu_survenance', models.TextField(blank=True, null=True)),
                ('tva_recuperee', models.TextField(blank=True, null=True)),
                ('fait_generateur', models.TextField(blank=True, null=True)),
                ('point_de_choc', models.TextField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('franchise', models.BigIntegerField(null=True)),
                ('date_survenance', models.DateTimeField(null=True)),
                ('date_declaration', models.DateTimeField(null=True)),
                ('date_ouverture', models.DateTimeField(null=True)),
                ('date_reouverture', models.DateTimeField(null=True)),
                ('date_cloture', models.DateTimeField(null=True)),
                ('sinistre_recours', models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non'), ('AUCUN', 'Aucun')], default='AUCUN', max_length=15, null=True)),
                ('statut', models.CharField(choices=[('ACCORDE', 'Accorde'), ('EN ATTENTE', 'Attente'), ('REJETE', 'Rejete'), ('EN RECOURS', 'En Recours'), ('SOLDE', 'Solde')], default='EN ATTENTE', max_length=15, null=True)),
                ('statut_validite', models.CharField(choices=[('VALIDE', 'Valide'), ('SUPPRIME', 'Supprime'), ('BROUILLON', 'Brouillon'), ('CLOTURE', 'Cloture')], default='BROUILLON', max_length=15, null=True)),
                ('statut_remboursement', models.CharField(choices=[('EN ATTENTE', 'Attente'), ('DEMANDE', 'Demande'), ('ACCEPTE', 'Accepte'), ('ACCEPTE PARTIELLEMENT', 'Accepte Partiellement'), ('REFUSE', 'Refuse'), ('ANNULE', 'Annule')], default='EN ATTENTE', max_length=25, null=True)),
                ('statut_paiement', models.CharField(choices=[('EN ATTENTE', 'Attente'), ('ORDONNANCE', 'Ordonnance'), ('PAYE', 'Paye')], default='EN ATTENTE', max_length=15, null=True)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('bureau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.bureau')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.client')),
                ('compagnie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.compagnie')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='histo_created_by_sinistre', to=settings.AUTH_USER_MODEL)),
                ('police', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.police')),
                ('responsabilite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.responsabilite')),
                ('sinistre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='sinistre.sinistre')),
                ('type_sinistre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.typesinistre')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='histo_updated_by_sinistre', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique Sinistres',
                'verbose_name_plural': 'Historique Sinistres',
                'db_table': 'historique_sinistres',
                'permissions': [('can_do_saisie_prestataire', 'Peut saisir des PEC en ligne'), ('can_do_saisie_gestionnaire', 'Peut saisir des PEC physiques'), ('can_view_prestations', 'Peut afficher les PEC'), ('can_do_generation_bordereau_facturation', 'Peut générer un bordereau de facturation'), ('can_view_bordereaux_facturations', 'Peut voir bordereaux de facturations'), ('can_view_facturesprestataires_en_attente', 'Peut voir les factures prestataire en attente'), ('can_view_facturesprestataires_validees', 'Peut voir les factures prestataire validées'), ('can_do_traitement_factures_prestataire', 'Peut traiter les factures prestataires'), ('can_view_remboursements_validees', 'Peut voir les remboursements validées'), ('can_do_ordonnancement', 'Peut faire un ordonnancement'), ('can_view_bordereaux_ordonnancement', "Peut voir les bordereaux d'ordonnancements"), ('can_do_annulation_sinistre', 'Peut annuler des sinistres'), ('can_do_annulation_facture', 'Peut annuler des factures')],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueSinistreIntervenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('historique_sinistre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='sinistre.historiquesinistre')),
                ('intervenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='sinistre.intervenant')),
            ],
            options={
                'verbose_name': 'Historique sinistre intervenant',
                'verbose_name_plural': 'Historique sinistre intervenant',
                'db_table': 'historique_sinistre_intervenant',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueGarantieSinistre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('franchise', models.BigIntegerField(null=True)),
                ('capital', models.BigIntegerField(null=True)),
                ('prime_nette', models.BigIntegerField(null=True)),
                ('prime_ttc', models.BigIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('circonstance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.circonstance')),
                ('garantie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.garantie')),
                ('historique_sinistre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='garanties', to='sinistre.historiquesinistre')),
            ],
            options={
                'verbose_name': 'Historique garantie sinistre',
                'verbose_name_plural': 'Historique garantie sinistre',
                'db_table': 'historique_garantie_sinistre',
            },
        ),
    ]
