# Generated by Django 3.2.15 on 2025-03-13 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0010_historiquegarantiesinistre_historiquesinistre_historiquesinistreintervenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementsinistre',
            name='historique_sinistre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='sinistre.historiquesinistre'),
        ),
    ]
