# Generated by Django 3.2.15 on 2025-03-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0011_mouvementsinistre_historique_sinistre'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementsinistre',
            name='date_cloture_sinistre',
            field=models.DateField(blank=True, null=True),
        ),
    ]
