# Generated by Django 3.2.15 on 2025-03-13 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0022_document_sinistre'),
        ('sinistre', '0012_mouvementsinistre_date_cloture_sinistre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementsinistre',
            name='motif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.motif'),
        ),
        migrations.AlterField(
            model_name='mouvementsinistre',
            name='mouvement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.mouvement'),
        ),
        migrations.AlterField(
            model_name='mouvementsinistre',
            name='police',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.police'),
        ),
        migrations.AlterField(
            model_name='mouvementsinistre',
            name='sinistre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='sinistre.sinistre'),
        ),
    ]
