# Generated by Django 3.2.15 on 2025-03-18 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0020_garantiecirconstance'),
        ('sinistre', '0013_auto_20250313_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiquesinistre',
            name='circonstance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.circonstance'),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='circonstance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.circonstance'),
        ),
    ]
