# Generated by Django 3.2.15 on 2025-03-20 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0020_garantiecirconstance'),
        ('production', '0022_document_sinistre'),
        ('sinistre', '0014_auto_20250318_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueProvision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimation', models.BigIntegerField(null=True)),
                ('deja_regle', models.BigIntegerField(null=True)),
                ('provision', models.BigIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('garantie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.garantie')),
                ('historique_sinistre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='provisions', to='sinistre.historiquesinistre')),
                ('poste_dommage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.postedommage')),
                ('sinistre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='sinistre.sinistre')),
            ],
            options={
                'verbose_name': 'Historique provisions',
                'verbose_name_plural': 'Historique provisions',
                'db_table': 'historique_provisions',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueAlimentPoliceSinistre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risque', models.TextField(blank=True, null=True)),
                ('aliment_police', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.alimentpolice')),
                ('historique_sinistre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='sinistre.historiquesinistre')),
                ('police', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.police')),
                ('sinistre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='sinistre.sinistre')),
            ],
            options={
                'verbose_name': 'Historique sinistre aliment police',
                'verbose_name_plural': 'Historique sinistre aliment police',
                'db_table': 'historique_aliment_police_sinistre',
            },
        ),
    ]
