# Generated by Django 3.2.15 on 2025-03-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0015_historiquealimentpolicesinistre_historiqueprovision'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiquesinistre',
            name='numero_provisoire',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='numero_provisoire',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
