# Generated by Django 3.2.15 on 2025-04-02 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0021_auto_20250402_0127'),
        ('production', '0023_auto_20250402_0127'),
        ('sinistre', '0016_auto_20250324_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='SinistreEtape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etape_sinistre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.etapesinistre')),
                ('mouvement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.mouvement')),
                ('sinistre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='sinistre.sinistre')),
            ],
            options={
                'verbose_name': 'Sinistre étape',
                'verbose_name_plural': 'Sinistre étape',
                'db_table': 'sinistre_etape',
            },
        ),
        migrations.RemoveField(
            model_name='demanderemboursementmobile',
            name='acte',
        ),
        migrations.RemoveField(
            model_name='demanderemboursementmobile',
            name='adherent_principal',
        ),
        migrations.RemoveField(
            model_name='demanderemboursementmobile',
            name='beneficiaire',
        ),
        migrations.RemoveField(
            model_name='demanderemboursementmobile',
            name='bureau',
        ),
        migrations.RemoveField(
            model_name='demanderemboursementmobile',
            name='mode_remboursement',
        ),
        migrations.RemoveField(
            model_name='demanderemboursementmobile',
            name='prestataire',
        ),
        migrations.RemoveField(
            model_name='sinistretemporaire',
            name='acte',
        ),
        migrations.RemoveField(
            model_name='sinistretemporaire',
            name='adherent_principal',
        ),
        migrations.RemoveField(
            model_name='sinistretemporaire',
            name='affection',
        ),
        migrations.RemoveField(
            model_name='sinistretemporaire',
            name='aliment',
        ),
        migrations.RemoveField(
            model_name='sinistretemporaire',
            name='approuved_by',
        ),
        migrations.RemoveField(
            model_name='sinistretemporaire',
            name='bareme',
        ),
        migrations.RemoveField(
            model_name='sinistretemporaire',
            name='compagnie',
        ),
        migrations.RemoveField(
            model_name='sinistretemporaire',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sinistretemporaire',
            name='dossier_sinistre',
        ),
        migrations.RemoveField(
            model_name='sinistretemporaire',
            name='formulegarantie',
        ),
        migrations.RemoveField(
            model_name='sinistretemporaire',
            name='medicament',
        ),
        migrations.RemoveField(
            model_name='sinistretemporaire',
            name='periode_couverture',
        ),
        migrations.RemoveField(
            model_name='sinistretemporaire',
            name='police',
        ),
        migrations.RemoveField(
            model_name='sinistretemporaire',
            name='prescripteur',
        ),
        migrations.RemoveField(
            model_name='sinistretemporaire',
            name='prestataire',
        ),
        migrations.RemoveField(
            model_name='sinistretemporaire',
            name='served_by',
        ),
        migrations.RemoveField(
            model_name='sinistretemporaire',
            name='updated_price_by',
        ),
        migrations.RemoveField(
            model_name='bordereauordonnancement',
            name='adherent_principal',
        ),
        migrations.RemoveField(
            model_name='dossiersinistre',
            name='aliment',
        ),
        migrations.RemoveField(
            model_name='factureprestataire',
            name='adherent_principal',
        ),
        migrations.RemoveField(
            model_name='paiementcomptable',
            name='adherent_principal',
        ),
        migrations.DeleteModel(
            name='ControlePlafond',
        ),
        migrations.DeleteModel(
            name='DemandeRemboursementMobile',
        ),
        migrations.DeleteModel(
            name='SinistreTemporaire',
        ),
    ]
