# Generated by Django 3.2.15 on 2025-04-02 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0017_auto_20250402_0127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historiquesinistre',
            options={'permissions': [('can_do_saisie_gestionnaire', 'Peut saisir des PEC physiques'), ('can_view_prestations', 'Peut afficher les PEC'), ('can_do_generation_bordereau_facturation', 'Peut générer un bordereau de facturation'), ('can_view_bordereaux_facturations', 'Peut voir bordereaux de facturations'), ('can_view_remboursements_validees', 'Peut voir les remboursements validées'), ('can_do_ordonnancement', 'Peut faire un ordonnancement'), ('can_view_bordereaux_ordonnancement', "Peut voir les bordereaux d'ordonnancements"), ('can_do_annulation_sinistre', 'Peut annuler des sinistres'), ('can_do_annulation_facture', 'Peut annuler des factures')], 'verbose_name': 'Historique Sinistres', 'verbose_name_plural': 'Historique Sinistres'},
        ),
        migrations.AlterModelOptions(
            name='sinistre',
            options={'permissions': [('can_do_saisie_gestionnaire', 'Peut saisir des PEC physiques'), ('can_view_prestations', 'Peut afficher les PEC'), ('can_do_generation_bordereau_facturation', 'Peut générer un bordereau de facturation'), ('can_view_bordereaux_facturations', 'Peut voir bordereaux de facturations'), ('can_view_remboursements_validees', 'Peut voir les remboursements validées'), ('can_do_ordonnancement', 'Peut faire un ordonnancement'), ('can_view_bordereaux_ordonnancement', "Peut voir les bordereaux d'ordonnancements"), ('can_do_annulation_sinistre', 'Peut annuler des sinistres'), ('can_do_annulation_facture', 'Peut annuler des factures')], 'verbose_name': 'Sinistres', 'verbose_name_plural': 'Sinistres'},
        ),
        migrations.RemoveField(
            model_name='bordereauordonnancement',
            name='prestataire',
        ),
        migrations.RemoveField(
            model_name='dossiersinistre',
            name='affection',
        ),
        migrations.RemoveField(
            model_name='dossiersinistre',
            name='centre_prescripteur',
        ),
        migrations.RemoveField(
            model_name='dossiersinistre',
            name='pharmacie',
        ),
        migrations.RemoveField(
            model_name='dossiersinistre',
            name='prescripteur',
        ),
        migrations.RemoveField(
            model_name='dossiersinistre',
            name='prestataire',
        ),
        migrations.RemoveField(
            model_name='paiementcomptable',
            name='prestataire',
        ),
        migrations.RemoveField(
            model_name='trackfacture',
            name='prestataire',
        ),
        migrations.RemoveField(
            model_name='trackfacture',
            name='reference_facture_prestataire',
        ),
        migrations.DeleteModel(
            name='FacturePrestataire',
        ),
    ]
