# Generated by Django 4.2.20 on 2025-04-03 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0020_sinistretemporaire_demanderemboursementmobile_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentDossierSinistre',
        ),
    ]
