# Generated by Django 4.2.20 on 2025-04-03 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0021_delete_documentdossiersinistre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demanderemboursementmobile',
            name='acte',
        ),
        migrations.RemoveField(
            model_name='demanderemboursementmobile',
            name='beneficiaire',
        ),
        migrations.RemoveField(
            model_name='demanderemboursementmobile',
            name='bureau',
        ),
        migrations.RemoveField(
            model_name='demanderemboursementmobile',
            name='mode_remboursement',
        ),
        migrations.DeleteModel(
            name='ControlePlafond',
        ),
        migrations.DeleteModel(
            name='DemandeRemboursementMobile',
        ),
    ]
