# Generated by Django 4.2.20 on 2025-04-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompteComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('libelle', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compte comptable',
                'verbose_name_plural': 'Comptes comptables',
                'db_table': 'compte_comptable',
            },
        ),
        migrations.CreateModel(
            name='EncaissementCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_com_courtage', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('montant_com_gestion', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('type_commission', models.CharField(choices=[('COURTAGE', 'Courtage'), ('GESTION', 'Gestion')], default=None, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Encaissement de commission',
                'verbose_name_plural': 'Encaissements de commissions',
                'db_table': 'encaissement_commission',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sens', models.CharField(blank=True, max_length=1, null=True)),
                ('montant', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journaux',
                'db_table': 'journal',
            },
        ),
    ]
