# Generated by Django 3.2.15 on 2025-01-11 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptabilite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0001_initial'),
        ('sinistre', '0001_initial'),
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BordereauOrdonnance',
            fields=[
            ],
            options={
                'verbose_name': 'Bord. ordonnancé',
                'verbose_name_plural': 'Bordx ordonnancés',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sinistre.bordereauordonnancement',),
        ),
        migrations.CreateModel(
            name='ReglementApporteurs',
            fields=[
            ],
            options={
                'verbose_name': 'Reglement apporteurs',
                'verbose_name_plural': 'Reglements apporteurs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('production.reglement',),
        ),
        migrations.CreateModel(
            name='ReglementReverseCompagnie',
            fields=[
            ],
            options={
                'verbose_name': 'Reglement compagnie',
                'verbose_name_plural': 'Reglements compagnie',
                'permissions': [('can_do_reglement_compagnie', 'Peut faire des règlements compagnies')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('production.reglement',),
        ),
        migrations.AddField(
            model_name='journal',
            name='bureau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configurations.bureau'),
        ),
        migrations.AddField(
            model_name='journal',
            name='compte_comptable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='comptabilite.comptecomptable'),
        ),
        migrations.AddField(
            model_name='journal',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journal',
            name='encaissement_commission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='journals', related_query_name='journal', to='comptabilite.encaissementcommission'),
        ),
        migrations.AddField(
            model_name='encaissementcommission',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encaissementcommission',
            name='operation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.operation'),
        ),
        migrations.AddField(
            model_name='encaissementcommission',
            name='reglement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='encaissement_commissions', related_query_name='encaissement_commission', to='production.reglement'),
        ),
        migrations.AddField(
            model_name='comptecomptable',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
