# Generated by Django 4.2.20 on 2025-04-03 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reglementreversecompagnie',
            options={'permissions': [('can_do_reglement_compagnie', 'Peut faire des règlements assureurs')], 'verbose_name': 'Reglement assureur', 'verbose_name_plural': 'Reglements assureur'},
        ),
    ]
