# Generated by Django 4.2.20 on 2025-04-05 14:45

import analysecontrole.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysePortefeuille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.ImageField(blank=True, null=True, upload_to=analysecontrole.models.upload_fichier_portefeuille)),
                ('type_portefeuille', models.CharField(choices=[('AUCUN', 'Aucun'), ('PAR COMPAGNIE', 'Par Cie'), ('TOUTES LES COMPAGNIES', 'All Cie'), ('PAR COMMERCIAL', 'Par Com'), ('TOUS LES COMMERCIAUX', 'All Com'), ('PAR BUSINESS UNIT', 'Par Bus'), ('TOUS LES BUSINESS UNIT', 'All Bus')], default='AUCUN', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Analyse portefeuille',
                'verbose_name_plural': 'Analyse portefeuille',
                'db_table': 'analyse_portefeuille',
            },
        ),
        migrations.CreateModel(
            name='ControleCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.ImageField(blank=True, null=True, upload_to=analysecontrole.models.upload_fichier_commission)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Contrôle commissions',
                'verbose_name_plural': 'Contrôle commissions',
                'db_table': 'controle_commission',
            },
        ),
    ]
