# Generated by Django 3.2.15 on 2025-02-10 08:48

import analysecontrole.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configurations', '0017_remove_garantie_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysePortefeuille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.ImageField(blank=True, null=True, upload_to=analysecontrole.models.upload_fichier_portefeuille)),
                ('type_portefeuille', models.CharField(choices=[('AUCUN', 'Aucun'), ('PAR COMPAGNIE', 'Par Cie'), ('TOUTES LES COMPAGNIES', 'All Cie'), ('PAR COMMERCIAL', 'Par Com'), ('TOUS LES COMMERCIAUX', 'All Com'), ('PAR BUSINESS UNIT', 'Par Bus'), ('TOUS LES BUSINESS UNIT', 'All Bus')], default='AUCUN', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.businessunit')),
                ('commercial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('compagnie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.compagnie')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='portefeuille_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analyse portefeuille',
                'verbose_name_plural': 'Analyse portefeuille',
                'db_table': 'analyse_portefeuille',
            },
        ),
    ]
