# Generated by Django 4.2.20 on 2025-04-05 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configurations', '0001_initial'),
        ('analysecontrole', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='controlecommission',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='controle_commision_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analyseportefeuille',
            name='business_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.businessunit'),
        ),
        migrations.AddField(
            model_name='analyseportefeuille',
            name='commercial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analyseportefeuille',
            name='compagnie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.compagnie'),
        ),
        migrations.AddField(
            model_name='analyseportefeuille',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='portefeuille_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
