# Generated by Django 3.2.15 on 2025-02-21 14:23

import analysecontrole.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analysecontrole', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.ImageField(blank=True, null=True, upload_to=analysecontrole.models.upload_fichier_commission)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='controle_commision_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contrôle des commissions',
                'verbose_name_plural': 'Contrôle des commissions',
                'db_table': 'controle_commission',
            },
        ),
    ]
