# Generated by Django 3.2.15 on 2025-03-05 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysecontrole', '0002_controlecommission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controlecommission',
            options={'verbose_name': 'Contrôle commissions', 'verbose_name_plural': 'Contrôle commissions'},
        ),
    ]
