# Generated by Django 3.2.15 on 2025-01-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typedocument',
            name='is_police_quittante_clt',
            field=models.BooleanField(default=False),
        ),
    ]
