# Generated by Django 4.2.20 on 2025-04-05 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiquealiment',
            name='autre_risque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.autrerisque'),
        ),
        migrations.AddField(
            model_name='historiquealiment',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='historiquealiment',
            name='libelle',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historiquealiment',
            name='modele',
            field=models.TextField(blank=True, null=True),
        ),
    ]
