# Generated by Django 3.2.15 on 2025-01-16 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0002_typedocument_is_police_quittante_clt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='gestionnaire',
        ),
        migrations.RemoveField(
            model_name='client',
            name='groupe_international',
        ),
        migrations.RemoveField(
            model_name='client',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='client',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='client',
            name='veos_assure_sante_idper',
        ),
        migrations.RemoveField(
            model_name='client',
            name='veos_client_idper',
        ),
        migrations.AddField(
            model_name='client',
            name='commercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='commercial_client', to=settings.AUTH_USER_MODEL),
        ),
    ]
