# Generated by Django 4.2.20 on 2025-04-05 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0002_historiquealiment_autre_risque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiquepolice',
            name='commercial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='histo_commercial', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historiquepolice',
            name='gestionnaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='histo_gestionnaire_sinistre', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historiquepolice',
            name='production',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='histo_production', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historiquepolice',
            name='police',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='historique_polices', to='production.police'),
        ),
    ]
