# Generated by Django 3.2.15 on 2025-01-17 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0009_groupe'),
        ('production', '0003_auto_20250116_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='groupe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.groupe'),
        ),
    ]
