# Generated by Django 4.2.20 on 2025-04-05 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0003_historiquepolice_commercial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='police',
            name='logo_partenaire',
        ),
        migrations.AddField(
            model_name='police',
            name='commercial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='commercial', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='police',
            name='gestionnaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='gestionnaire_sinistre', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='police',
            name='production',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='production', to=settings.AUTH_USER_MODEL),
        ),
    ]
