# Generated by Django 3.2.15 on 2025-01-18 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_client_groupe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiquepolice',
            name='type_assurance',
        ),
        migrations.RemoveField(
            model_name='police',
            name='type_assurance',
        ),
    ]
