# Generated by Django 4.2.20 on 2025-04-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_remove_police_logo_partenaire_police_commercial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typedocument',
            name='is_production',
            field=models.BooleanField(default=False),
        ),
    ]
