# Generated by Django 3.2.15 on 2025-01-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_auto_20250118_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiquepolice',
            name='date_fin_effet',
            field=models.DateField(null=True),
        ),
    ]
