# Generated by Django 4.2.20 on 2025-04-05 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_typedocument_is_production'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typedocument',
            name='is_police_quittante_clt',
        ),
    ]
