# Generated by Django 3.2.15 on 2025-01-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_alter_historiquepolice_date_fin_effet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filiale',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
    ]
