# Generated by Django 4.2.20 on 2025-04-05 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0005_remove_garantie_deleted_at'),
        ('production', '0006_remove_typedocument_is_police_quittante_clt'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvement',
            name='type_mouvement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.typemouvement'),
        ),
    ]
