# Generated by Django 3.2.15 on 2025-01-24 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_alter_filiale_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiquealiment',
            name='autre_risque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.autrerisque'),
        ),
        migrations.AddField(
            model_name='historiquealiment',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='historiquealiment',
            name='libelle',
            field=models.TextField(null=True),
        ),
    ]
