# Generated by Django 4.2.20 on 2025-04-10 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_mouvement_type_mouvement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentpolice',
            name='vehicule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='alimentpolice', to='production.vehicule'),
        ),
        migrations.AlterField(
            model_name='historiquealiment',
            name='vehicule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='historiquevehicule', to='production.vehicule'),
        ),
    ]
