# Generated by Django 3.2.15 on 2025-02-10 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_auto_20250124_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementpolice',
            name='police',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='mouvements', to='production.police'),
        ),
    ]
