# Generated by Django 4.2.20 on 2025-04-22 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0008_alter_alimentpolice_vehicule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodecouverture',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
