# Generated by Django 3.2.15 on 2025-02-10 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_alter_mouvementpolice_police'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='police',
            name='logo_partenaire',
        ),
    ]
