# Generated by Django 3.2.15 on 2025-02-10 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0010_remove_police_logo_partenaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiquepolice',
            name='commercial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='histo_commercial', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historiquepolice',
            name='gestionnaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='histo_gestionnaire_sinistre', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='police',
            name='commercial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='commercial', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='police',
            name='gestionnaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='gestionnaire_sinistre', to=settings.AUTH_USER_MODEL),
        ),
    ]
