# Generated by Django 3.2.15 on 2025-02-10 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0011_auto_20250210_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiquepolice',
            name='production',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='histo_production', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='police',
            name='production',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='production', to=settings.AUTH_USER_MODEL),
        ),
    ]
