# Generated by Django 3.2.15 on 2025-02-11 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0012_auto_20250210_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriquePoliceGarantie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('franchise', models.FloatField(blank=True, null=True)),
                ('capital', models.FloatField(blank=True, null=True)),
                ('statut', models.CharField(blank=True, choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif')], default='ACTIF', max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('police_garantie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.policegarantie')),
            ],
            options={
                'verbose_name': 'Historique Police Garanties',
                'verbose_name_plural': 'Historique Police Garanties',
                'db_table': 'historique_police_garantie',
            },
        ),
    ]
