# Generated by Django 3.2.15 on 2025-02-11 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0017_remove_garantie_deleted_at'),
        ('production', '0013_historiquepolicegarantie'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiquepolicegarantie',
            name='formule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.formule'),
        ),
        migrations.AddField(
            model_name='historiquepolicegarantie',
            name='garantie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.garantie'),
        ),
    ]
