# Generated by Django 3.2.15 on 2025-02-12 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_auto_20250211_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiquepolicegarantie',
            name='police',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.police'),
        ),
    ]
