# Generated by Django 3.2.15 on 2025-02-12 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_historiquepolicegarantie_police'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historiquepolice',
            old_name='garantie',
            new_name='garantie_rep',
        ),
    ]
