# Generated by Django 3.2.15 on 2025-02-12 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0016_rename_garantie_historiquepolice_garantie_rep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historiquepolice',
            old_name='garantie_rep',
            new_name='garantie',
        ),
    ]
