# Generated by Django 3.2.15 on 2025-02-13 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0017_rename_garantie_rep_historiquepolice_garantie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiquealiment',
            name='modele',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='modele',
            field=models.TextField(blank=True, null=True),
        ),
    ]
