# Generated by Django 3.2.15 on 2025-03-05 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0018_auto_20250213_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiquepolice',
            name='police',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='historique_polices', to='production.police'),
        ),
        migrations.AlterField(
            model_name='policeassureur',
            name='historique_police',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='police_assureurs', to='production.historiquepolice'),
        ),
    ]
