# Generated by Django 3.2.15 on 2025-03-05 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0019_auto_20250305_0256'),
        ('production', '0019_auto_20250305_0116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typedocument',
            old_name='is_police_quittante_clt',
            new_name='is_production',
        ),
        migrations.AddField(
            model_name='motif',
            name='etat_sinistre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mouvement',
            name='type_mouvement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.typemouvement'),
        ),
        migrations.AddField(
            model_name='quittance',
            name='montant_cout_police_courtier_regle',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reglement',
            name='montant_police_courtier',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True),
        ),
    ]
