# Generated by Django 3.2.15 on 2025-03-10 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0020_auto_20250305_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='aliment',
        ),
    ]
