# Generated by Django 3.2.15 on 2025-03-13 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0009_alter_garantiesinistre_sinistre'),
        ('production', '0021_remove_document_aliment'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='sinistre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sinistre', to='sinistre.sinistre'),
        ),
    ]
