# Generated by Django 3.2.15 on 2025-04-02 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0022_document_sinistre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aliment',
            name='adherent_principal',
        ),
        migrations.RemoveField(
            model_name='aliment',
            name='bureau',
        ),
        migrations.RemoveField(
            model_name='aliment',
            name='civilite',
        ),
        migrations.RemoveField(
            model_name='aliment',
            name='pays_activite_professionnelle',
        ),
        migrations.RemoveField(
            model_name='aliment',
            name='pays_naissance',
        ),
        migrations.RemoveField(
            model_name='aliment',
            name='pays_residence',
        ),
        migrations.RemoveField(
            model_name='aliment',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='aliment',
            name='qualite_beneficiaire',
        ),
        migrations.RemoveField(
            model_name='aliment',
            name='user_extranet',
        ),
        migrations.RemoveField(
            model_name='alimentformule',
            name='aliment',
        ),
        migrations.RemoveField(
            model_name='alimentformule',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='alimentformule',
            name='formule',
        ),
        migrations.RemoveField(
            model_name='alimenttemporaire',
            name='aliment',
        ),
        migrations.RemoveField(
            model_name='alimenttemporaire',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='carte',
            name='aliment',
        ),
        migrations.RemoveField(
            model_name='carte',
            name='bureau',
        ),
        migrations.RemoveField(
            model_name='mouvementaliment',
            name='aliment',
        ),
        migrations.RemoveField(
            model_name='mouvementaliment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='mouvementaliment',
            name='mouvement',
        ),
        migrations.RemoveField(
            model_name='mouvementaliment',
            name='police',
        ),
        migrations.RemoveField(
            model_name='photoidentite',
            name='aliment',
        ),
    ]
