# Generated by Django 3.2.15 on 2025-04-02 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0017_auto_20250402_0127'),
        ('production', '0023_auto_20250402_0127'),
        #('grh', '0002_auto_20250402_0127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aliment',
        ),
        migrations.DeleteModel(
            name='AlimentFormule',
        ),
        migrations.DeleteModel(
            name='AlimentTemporaire',
        ),
        migrations.DeleteModel(
            name='Carte',
        ),
        migrations.DeleteModel(
            name='MouvementAliment',
        ),
        migrations.DeleteModel(
            name='PhotoIdentite',
        ),
    ]
