# Generated by Django 3.2.15 on 2025-04-02 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0024_auto_20250402_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarifprestataireclient',
            name='client',
        ),
        migrations.RemoveField(
            model_name='tarifprestataireclient',
            name='formule',
        ),
        migrations.RemoveField(
            model_name='tarifprestataireclient',
            name='prestataire',
        ),
        migrations.RemoveField(
            model_name='formulegarantie',
            name='reseau_soin',
        ),
        migrations.DeleteModel(
            name='Bareme',
        ),
        migrations.DeleteModel(
            name='TarifPrestataireClient',
        ),
    ]
