# Generated by Django 3.2.15 on 2025-04-02 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0025_auto_20250402_0307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policeclient',
            name='client',
        ),
        migrations.RemoveField(
            model_name='policeclient',
            name='police',
        ),
        migrations.RemoveField(
            model_name='vehiculepolice',
            name='formule',
        ),
        migrations.RemoveField(
            model_name='vehiculepolice',
            name='police',
        ),
        migrations.RemoveField(
            model_name='vehiculepolice',
            name='vehicule',
        ),
        migrations.DeleteModel(
            name='CarteDigitalDematerialisee',
        ),
        migrations.DeleteModel(
            name='PoliceClient',
        ),
        migrations.DeleteModel(
            name='VehiculePolice',
        ),
    ]
