# Generated by Django 3.2.15 on 2025-04-02 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0026_auto_20250402_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculePolice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(blank=True, max_length=255, null=True)),
                ('date_mouvement', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(blank=True, choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif')], default='ACTIF', max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.formulegarantie')),
                ('police', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='production.police')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='production.vehicule')),
            ],
            options={
                'verbose_name': 'Véhicule de la police',
                'verbose_name_plural': 'Véhicules de la police',
                'db_table': 'vehicule_police',
            },
        ),
        migrations.CreateModel(
            name='PoliceClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('observation', models.CharField(blank=True, max_length=255, null=True)),
                ('statut', models.CharField(blank=True, choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif')], default='ACTIF', max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='production.client')),
                ('police', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='production.police')),
            ],
            options={
                'verbose_name': 'Client police',
                'verbose_name_plural': 'Clients-polices',
                'db_table': 'client_police',
            },
        ),
        migrations.CreateModel(
            name='CarteDigitalDematerialisee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_digital_card', models.BooleanField(default=False)),
                ('digital_card_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carte Digital Dématérialisée',
                'verbose_name_plural': 'Cartes Digital Dématérialisées',
                'db_table': 'cartes_digital_dematerialisees',
            },
        ),
    ]
