# Generated by Django 4.2.20 on 2025-04-03 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0028_aliment_remove_document_sinistre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aliment',
            name='has_photo_veos',
        ),
        migrations.RemoveField(
            model_name='aliment',
            name='statut_import_photo_veos',
        ),
        migrations.RemoveField(
            model_name='aliment',
            name='veos_adherent_principal',
        ),
        migrations.RemoveField(
            model_name='aliment',
            name='veos_adherent_principal_id_per',
        ),
        migrations.RemoveField(
            model_name='aliment',
            name='veos_code_aliment',
        ),
        migrations.RemoveField(
            model_name='aliment',
            name='veos_code_college',
        ),
        migrations.RemoveField(
            model_name='aliment',
            name='veos_code_formule',
        ),
        migrations.RemoveField(
            model_name='aliment',
            name='veos_code_qualite_beneficiaire',
        ),
        migrations.RemoveField(
            model_name='aliment',
            name='veos_id_npol',
        ),
        migrations.RemoveField(
            model_name='aliment',
            name='veos_numero_carte',
        ),
    ]
