# Generated by Django 4.2.20 on 2025-04-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0002_recours'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recours',
        ),
        migrations.AddField(
            model_name='categorievehicule',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
