# Generated by Django 3.2.15 on 2025-01-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeFichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type de fichier',
                'verbose_name_plural': 'Type de fichier',
                'db_table': 'type_fichier',
            },
        ),
    ]
