# Generated by Django 3.2.15 on 2025-01-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0003_typefichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='typefichier',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
