# Generated by Django 4.2.20 on 2025-04-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0003_delete_recours_categorievehicule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fractionnement',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
