# Generated by Django 4.2.20 on 2025-04-05 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0004_fractionnement_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garantie',
            name='deleted_at',
        ),
    ]
