# Generated by Django 3.2.15 on 2025-01-14 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0004_typefichier_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typefichier',
            old_name='status',
            new_name='statut',
        ),
    ]
