# Generated by Django 3.2.15 on 2025-01-16 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0005_rename_status_typefichier_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='prestataire',
        ),
        migrations.RemoveField(
            model_name='user',
            name='veos_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='veos_code_prestataire',
        ),
    ]
