# Generated by Django 4.2.20 on 2025-04-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0005_remove_garantie_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('libelle', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statut', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Recours sur un sinistre',
                'verbose_name_plural': 'Recours sur un sinistre',
                'db_table': 'recours',
            },
        ),
    ]
