# Generated by Django 3.2.15 on 2025-01-16 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0006_auto_20250116_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='client_grh',
        ),
        migrations.RemoveField(
            model_name='user',
            name='utilisateur_grh',
        ),
    ]
