# Generated by Django 4.2.20 on 2025-04-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0006_recours'),
    ]

    operations = [
        migrations.AddField(
            model_name='recours',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
