# Generated by Django 3.2.15 on 2025-01-16 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0007_auto_20250116_1653'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
