# Generated by Django 4.2.20 on 2025-04-06 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0007_recours_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recours',
        ),
    ]
