# Generated by Django 3.2.15 on 2025-01-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0008_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statut', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Groupes',
                'verbose_name_plural': 'Groupes',
                'db_table': 'groupes',
            },
        ),
    ]
