# Generated by Django 4.2.20 on 2025-04-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0008_delete_recours'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapeSinistre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_ordre', models.CharField(blank=True, max_length=100, null=True)),
                ('libelle', models.CharField(blank=True, max_length=100, null=True)),
                ('type_etape', models.CharField(choices=[('Facultatif', 'Facultatif'), ('Obligatoire', 'Obligatoire')], default='Facultatif', max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statut', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Etape de suivi sinistre',
                'verbose_name_plural': 'Etape de suivi sinistre',
                'db_table': 'etape_sinistre',
            },
        ),
    ]
