# Generated by Django 3.2.15 on 2025-01-20 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0009_groupe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carburant',
            options={'verbose_name': 'Carburants', 'verbose_name_plural': 'Energies'},
        ),
        migrations.AlterModelOptions(
            name='compagnie',
            options={'verbose_name': 'Compagnie', 'verbose_name_plural': 'Assureurs'},
        ),
        migrations.RemoveField(
            model_name='compagnie',
            name='groupe_compagnie',
        ),
    ]
