# Generated by Django 4.2.20 on 2025-04-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0009_etapesinistre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapesinistre',
            name='numero_ordre',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name='etapesinistre',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_code_etape'),
        ),
        migrations.AddConstraint(
            model_name='etapesinistre',
            constraint=models.UniqueConstraint(fields=('numero_ordre',), name='unique_ordre_etape'),
        ),
    ]
