# Generated by Django 4.2.20 on 2025-04-08 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0010_alter_etapesinistre_numero_ordre_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RisqueProduit',
            new_name='TauxCommission',
        ),
        migrations.AlterModelOptions(
            name='tauxcommission',
            options={'verbose_name': 'Taux de commission', 'verbose_name_plural': 'Taux de commission'},
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='risque_produit',
            new_name='taux_commission',
        ),
        migrations.AlterModelTable(
            name='tauxcommission',
            table='taux_commision',
        ),
    ]
