# Generated by Django 3.2.15 on 2025-01-20 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0010_auto_20250120_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='RisqueProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Risques du produit',
                'verbose_name_plural': 'Risques du produit',
                'db_table': 'risque_produit',
            },
        ),
        migrations.AddField(
            model_name='produit',
            name='risque_produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.risqueproduit'),
        ),
    ]
