# Generated by Django 3.2.15 on 2025-01-20 10:28

import configurations.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0011_auto_20250120_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='risqueproduit',
            name='taux',
            field=configurations.models.FloatRangeField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
