# Generated by Django 3.2.15 on 2025-01-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0012_risqueproduit_taux'),
    ]

    operations = [
        migrations.AddField(
            model_name='carosserie',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
