# Generated by Django 3.2.15 on 2025-01-23 17:14

import configurations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0013_carosserie_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bureau',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=configurations.models.upload_logo_location_bureau),
        ),
    ]
