# Generated by Django 3.2.15 on 2025-01-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0014_bureau_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorievehicule',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
