# Generated by Django 3.2.15 on 2025-01-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0015_categorievehicule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fractionnement',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
