# Generated by Django 3.2.15 on 2025-01-28 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0016_fractionnement_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garantie',
            name='deleted_at',
        ),
    ]
