# Generated by Django 3.2.15 on 2025-03-05 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0017_remove_garantie_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
