# Generated by Django 3.2.15 on 2025-03-05 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0018_auto_20250305_0240'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosteDommage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('libelle', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statut', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Postes de dommages',
                'verbose_name_plural': 'Postes de dommages',
                'db_table': 'poste_dommage',
            },
        ),
        migrations.CreateModel(
            name='Responsabilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=100, null=True)),
                ('taux_responsabilite', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statut', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Responsabilités',
                'verbose_name_plural': 'Responsabilités',
                'db_table': 'responsabilite',
            },
        ),
        migrations.CreateModel(
            name='TypeIntervenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statut', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Type d'intervenant",
                'verbose_name_plural': "Type d'intervenant",
                'db_table': 'type_intervenant',
            },
        ),
        migrations.CreateModel(
            name='TypeMouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statut', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Type de mouvement',
                'verbose_name_plural': 'Type de mouvement',
                'db_table': 'type_mouvement',
            },
        ),
        migrations.CreateModel(
            name='TypeSinistre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statut', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Type de sinistre',
                'verbose_name_plural': 'Type de sinistre',
                'db_table': 'type_sinistre',
            },
        ),
        migrations.AlterModelOptions(
            name='typeproduit',
            options={'verbose_name': 'Type de produit', 'verbose_name_plural': 'Type de produit'},
        ),
        migrations.CreateModel(
            name='Circonstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('libelle', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statut', models.BooleanField(default=True)),
                ('branche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.branche')),
            ],
            options={
                'verbose_name': 'Circonstances',
                'verbose_name_plural': 'Circonstances',
                'db_table': 'circonstance',
            },
        ),
    ]
