# Generated by Django 3.2.15 on 2025-03-11 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0019_auto_20250305_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarantieCirconstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('circonstance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.circonstance')),
                ('garantie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.garantie')),
            ],
            options={
                'verbose_name': 'Garanties / Circonstances',
                'verbose_name_plural': 'Garanties / Circonstances',
                'db_table': 'garantie_circonstance',
            },
        ),
    ]
