# Generated by Django 3.2.15 on 2025-04-02 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0020_garantiecirconstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapeSinistre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('libelle', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('Facultatif', 'Facultatif'), ('Obligatoire', 'Obligatoire')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Etape sinistre',
                'verbose_name_plural': 'Etape sinistre',
                'db_table': 'etape_sinistre',
            },
        ),
        migrations.DeleteModel(
            name='AlimentVeos',
        ),
        migrations.DeleteModel(
            name='ApporteurVeos',
        ),
        migrations.DeleteModel(
            name='ClientVeos',
        ),
        migrations.DeleteModel(
            name='CompagnieVeos',
        ),
        migrations.DeleteModel(
            name='ComptePrestataireVeos',
        ),
        migrations.DeleteModel(
            name='FormuleVeos',
        ),
        migrations.DeleteModel(
            name='PeriodeVeos',
        ),
        migrations.DeleteModel(
            name='PoliceVeos',
        ),
        migrations.DeleteModel(
            name='PrescripteurVeos',
        ),
        migrations.DeleteModel(
            name='PrestataireVeos',
        ),
        migrations.DeleteModel(
            name='QuittanceVeos',
        ),
        migrations.DeleteModel(
            name='SinistreVeos',
        ),
        migrations.DeleteModel(
            name='UtilisateurGrhVeos',
        ),
        migrations.DeleteModel(
            name='UtilisateurVeos',
        ),
        migrations.RemoveField(
            model_name='naturequittance',
            name='code_veos',
        ),
        migrations.RemoveField(
            model_name='prescripteur',
            name='veos_code_specialite',
        ),
        migrations.RemoveField(
            model_name='prescripteur',
            name='veos_id_per',
        ),
        migrations.RemoveField(
            model_name='prestataire',
            name='veos_code_soc',
        ),
        migrations.RemoveField(
            model_name='prestataire',
            name='veos_type_pres',
        ),
        migrations.RemoveField(
            model_name='typeprestataire',
            name='veos_code',
        ),
        migrations.RemoveField(
            model_name='typequittance',
            name='code_veos',
        ),
    ]
