# Generated by Django 3.2.15 on 2025-04-02 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0022_auto_20250402_0307'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Affection',
        ),
        migrations.DeleteModel(
            name='CategorieAffection',
        ),
    ]
