# Generated by Django 3.2.15 on 2025-04-02 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0023_auto_20250402_0312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialitetypepresta',
            name='specialite',
        ),
        migrations.RemoveField(
            model_name='specialitetypepresta',
            name='type_prestataire',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='prestataire',
        ),
        migrations.RemoveField(
            model_name='retenue',
            name='type_prestataire',
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='coef_prestataire',
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='cout_prestataire',
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='lettre_cle_prestataire',
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='prestataire',
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='pu_prestataire',
        ),
        migrations.DeleteModel(
            name='Prestataire',
        ),
        migrations.DeleteModel(
            name='SpecialiteTypePresta',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='TypePrestataire',
        ),
    ]
