# Generated by Django 3.2.15 on 2025-04-02 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0024_auto_20250402_0320'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlimentBaobab',
        ),
        migrations.RemoveField(
            model_name='caution',
            name='bureau',
        ),
        migrations.RemoveField(
            model_name='caution',
            name='compagnie',
        ),
        migrations.RemoveField(
            model_name='caution',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='ChangementFormule',
        ),
        migrations.DeleteModel(
            name='MarqueVehicule',
        ),
        migrations.RemoveField(
            model_name='prescripteur',
            name='bureau',
        ),
        migrations.RemoveField(
            model_name='prescripteur',
            name='specialite',
        ),
        migrations.DeleteModel(
            name='Profession',
        ),
        migrations.DeleteModel(
            name='RegroupPersonnel',
        ),
        migrations.DeleteModel(
            name='Caution',
        ),
        migrations.DeleteModel(
            name='Prescripteur',
        ),
    ]
