# Generated by Django 3.2.15 on 2025-04-02 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0025_auto_20250402_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlimentBaobab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_benef', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('naissance', models.CharField(blank=True, max_length=100, null=True)),
                ('sexe', models.CharField(blank=True, max_length=100, null=True)),
                ('carte', models.CharField(blank=True, max_length=100, null=True)),
                ('lien', models.CharField(blank=True, max_length=100, null=True)),
                ('famille', models.CharField(blank=True, max_length=100, null=True)),
                ('etat', models.CharField(blank=True, max_length=100, null=True)),
                ('entree', models.CharField(blank=True, max_length=100, null=True)),
                ('sortie', models.CharField(blank=True, max_length=100, null=True)),
                ('formule', models.CharField(blank=True, max_length=100, null=True)),
                ('formule_id', models.CharField(blank=True, max_length=100, null=True)),
                ('statut_traitement', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Aliment Baobab',
                'verbose_name_plural': 'Aliments Baobab',
                'db_table': 'aliment_baobab',
            },
        ),
        migrations.CreateModel(
            name='ChangementFormule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOM', models.CharField(max_length=100, null=True)),
                ('PRENOMS', models.CharField(max_length=100, null=True)),
                ('NUMERO_CARTE', models.CharField(max_length=100, null=True)),
                ('QUALITE_BENEFICIAIRE', models.CharField(max_length=100, null=True)),
                ('LIB_FORMULE', models.CharField(max_length=100, null=True)),
                ('CD_FORMULE', models.CharField(max_length=100, null=True)),
                ('DATE_DEBUT', models.DateField(null=True)),
                ('MOTIF', models.CharField(max_length=255, null=True)),
                ('STATUT_IMPORT', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Changement formule',
                'verbose_name_plural': 'Changements formule',
                'db_table': 'changement_formule',
            },
        ),
        migrations.CreateModel(
            name='MarqueVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marque',
                'verbose_name_plural': 'Marques',
                'db_table': 'marque_vehicule',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Profession',
                'verbose_name_plural': 'Professions',
                'db_table': 'professions',
            },
        ),
        migrations.CreateModel(
            name='RegroupPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Regroupement Personne',
                'verbose_name_plural': 'Regroupement Personnes',
                'db_table': 'regroup_personne',
            },
        ),
        migrations.CreateModel(
            name='Prescripteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('prenoms', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_ordre', models.CharField(blank=True, max_length=50, null=True)),
                ('telephone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('statut', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('bureau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.bureau')),
                ('specialite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.specialite')),
            ],
            options={
                'verbose_name': 'Prescripteur',
                'verbose_name_plural': 'Prescripteurs',
                'db_table': 'prescripteur',
            },
        ),
        migrations.CreateModel(
            name='Caution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.BigIntegerField()),
                ('date_debut_effet', models.DateTimeField(default=None)),
                ('date_fin_effet', models.DateTimeField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('bureau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.bureau')),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configurations.compagnie')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caution',
                'verbose_name_plural': 'Cautions',
                'db_table': 'caution',
            },
        ),
    ]
