# Generated by Django 4.2.20 on 2025-04-03 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0027_acte_categorieaffection_prestataire_regroupementacte_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paramwsboby',
            name='ws_boby',
        ),
        migrations.DeleteModel(
            name='StatExcelWsBoby',
        ),
        migrations.DeleteModel(
            name='ParamWsBoby',
        ),
        migrations.DeleteModel(
            name='WsBoby',
        ),
    ]
